# Tensor Broad Casting
the rules of broadcasting are....

*   Each tensor must have atleast one dimension .. no empty tensors
*   Comparing the dimension sizes of two tensor going from last to first.

*   Each dimension must be equal ,or
*   One of the dimension must be size of 1

*   The dimension doesnot exist in one of the tensors








In [1]:
import torch

In [2]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.8385, 0.8977, 0.1853, 0.6832],
        [0.0865, 0.0820, 0.9564, 0.8931]])
tensor([[1.6771, 1.7954, 0.3705, 1.3664],
        [0.1729, 0.1641, 1.9128, 1.7862]])


just clarification

In [3]:
rand*torch.ones(1,4)

tensor([[0.8385, 0.8977, 0.1853, 0.6832],
        [0.0865, 0.0820, 0.9564, 0.8931]])

# The above rules and allow broadcasting

In [4]:
a =  torch.ones(4,3,2)
b = a * torch.rand(  3,2)
print(b)

c = a * torch.rand(  3,1)
print(c)

d = a * torch.rand(  1,2)
print(d)

tensor([[[0.5717, 0.6596],
         [0.3026, 0.8814],
         [0.4583, 0.0497]],

        [[0.5717, 0.6596],
         [0.3026, 0.8814],
         [0.4583, 0.0497]],

        [[0.5717, 0.6596],
         [0.3026, 0.8814],
         [0.4583, 0.0497]],

        [[0.5717, 0.6596],
         [0.3026, 0.8814],
         [0.4583, 0.0497]]])
tensor([[[0.3714, 0.3714],
         [0.4939, 0.4939],
         [0.9471, 0.9471]],

        [[0.3714, 0.3714],
         [0.4939, 0.4939],
         [0.9471, 0.9471]],

        [[0.3714, 0.3714],
         [0.4939, 0.4939],
         [0.9471, 0.9471]],

        [[0.3714, 0.3714],
         [0.4939, 0.4939],
         [0.9471, 0.9471]]])
tensor([[[0.6705, 0.1547],
         [0.6705, 0.1547],
         [0.6705, 0.1547]],

        [[0.6705, 0.1547],
         [0.6705, 0.1547],
         [0.6705, 0.1547]],

        [[0.6705, 0.1547],
         [0.6705, 0.1547],
         [0.6705, 0.1547]],

        [[0.6705, 0.1547],
         [0.6705, 0.1547],
         [0.6705, 0.1547]]])


# through a run time erro because array will not be equal...


In [5]:
a = torch.ones(4,3,2)
b = a * torch.rand(4,3)
c = a * torch.rand(  2,3)
d = a * torch.rand(0,3)

RuntimeError: ignored

In [8]:
import math

In [9]:

# common functions
a = torch.rand(2,4)*2 -1
print("Common Functions")
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a,-0.5,0.5))

# trignometric functions and their inverses
angles = torch.tensor([0, math.pi / 4,math.pi/2,3 * math.pi/4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print("\nSine and arcsine")
print(angles)
print(sines)
print(inverses)

#biwise operation..
print("\n Bitwise XOR")
b = torch.tensor([1,5,11])
c = torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

#Comparisons..
print("\n Broadcasted-element wise equality Comparison")
d = torch.tensor([[1.,2.],[3.,4.]])
e = torch.ones(1,2)
print(torch.eq(d,e))

# reductions..
print("\n Broadcasted , element wise equality Comparison")
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1,2,1,2,1,2])))

# vector and Linear algebra operations..
print("\n Reduction ops")
v1 = torch.tensor([1.,0.,0.])
v2 = torch.tensor([0.,1.,0.])
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.],[0.,3.]])

print("\n vector & matrices")
print(torch.cross(v2,v1))
print(m1)
m3 = torch.matmul(m1,m2)
print(m3)
print(torch.svd(m3))

Common Functions
tensor([[0.8664, 0.7485, 0.1282, 0.1227],
        [0.6373, 0.1089, 0.6874, 0.8268]])
tensor([[-0., -0., -0., -0.],
        [1., -0., -0., -0.]])
tensor([[-1., -1., -1., -1.],
        [ 0., -1., -1., -1.]])
tensor([[-0.5000, -0.5000, -0.1282, -0.1227],
        [ 0.5000, -0.1089, -0.5000, -0.5000]])

Sine and arcsine
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

 Bitwise XOR
tensor([3, 2, 1])

 Broadcasted-element wise equality Comparison
tensor([[ True, False],
        [False, False]])

 Broadcasted , element wise equality Comparison
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

 Reduction ops

 vector & matrices
tensor([ 0.,  0., -1.])
tensor([[0.0716, 0.5681],
        [0.3546, 0.8428]])
tensor([[0.2147, 1.7043],
        [1.0638, 2.5284]])
torch.return_types.svd(
U=tensor([[-0.5244, -0.8515],
        [-0.8515,  0.5244]]),
S=tensor([3.2123, 0.3954]),
V=tensor([[-0.31

# Underscore _()

In [12]:
a = torch.tensor([0, math.pi / 4,math.pi/2,3 * math.pi/4])
print("a")
print(a)
print(torch.sin(a)) # creates new tensor, but a has not changed
print(a)

print("b")
b = torch.tensor([0, math.pi / 4,math.pi/2,3 * math.pi/4])
print(b)
print(torch.sin_(a))
print(a)


a
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])
b
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


# Functions that behave similarly

In [13]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print("Before")
print(a)
print(b)

print("\n After adding")
print(a.add_(b))
print(a)
print(b)

print("after  multiplying")
print(b.mul_(b))
print(b)

Before
tensor([[0.1739, 0.8802],
        [0.1140, 0.6058]])
tensor([[0.1828, 0.8569],
        [0.4234, 0.0102]])

 After adding
tensor([[0.3567, 1.7371],
        [0.5374, 0.6160]])
tensor([[0.3567, 1.7371],
        [0.5374, 0.6160]])
tensor([[0.1828, 0.8569],
        [0.4234, 0.0102]])
after  multiplying
tensor([[3.3407e-02, 7.3427e-01],
        [1.7930e-01, 1.0452e-04]])
tensor([[3.3407e-02, 7.3427e-01],
        [1.7930e-01, 1.0452e-04]])


# Another..

In [14]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.rand(2,2)
old_id = id(c) # get the id of the object..

print(c)
d = torch.matmul(a,b ,out=c)
print(c)

assert c is d
assert id(c),old_id

torch.rand(2,2, out=c)
print(c)
assert id(c),old_id

tensor([[0.2966, 0.8623],
        [0.3478, 0.7690]])
tensor([[0.1738, 0.3001],
        [0.2220, 0.3506]])
tensor([[0.6437, 0.2202],
        [0.2972, 0.9608]])


# we change a and b is also altered

In [16]:
a = torch.ones(2,2)
b = a

a[0][1]= 561
print(b)
print(a)

tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[  1., 561.],
        [  1.,   1.]])


# The clone method

In [19]:
a = torch.ones(2,2)
b = a.clone()

assert b is not a
print(torch.eq(a,b))
a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


# Aware of when using clone ()

In [20]:
a = torch.ones(2,2, requires_grad=True)
print(a)
b =  a.clone()
print(b)
c = a.detach().clone()
print(c)

print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<CloneBackward>)
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


# Changing the number of dimensions..

In [24]:
a = torch.rand(3,226,226)
b = a.unsqueeze(0) # the un sequeeze method adds the dimension of extent 1 , unsequeeze(0) adds its a new zeroth dimension. 
# when you have a  batch of one, extent 1 doesnot change the number of elements in the tensor...

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [26]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.4095]]]]])


In [27]:
a = torch.rand(1,20)
print(a.shape)
print(a)

torch.Size([1, 20])
tensor([[0.3451, 0.4668, 0.4022, 0.7060, 0.7799, 0.4996, 0.3577, 0.0943, 0.9337,
         0.3552, 0.3595, 0.0127, 0.6167, 0.9238, 0.8388, 0.6707, 0.4446, 0.9444,
         0.9476, 0.7431]])


# Convert numpy into Tensor

In [29]:
import numpy as np
numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
